### ISSUE TITLE
Improve usability

### ISSUE THREAD

**Issue by maxfreu** [tpapp/MarkdownTables.jl#3]
Hi! I have following table and output:

```julia
asdf = DataFrame(:id => [1,2,3], :val => [1,2,3])
asdf |> markdown_table()
# returns: DisplayAs.Raw.Showable{MIME{Symbol("text/markdown")}}(UInt8[0x7c, 0x20, 0x69, 0x64, 0x20, 0x7c, 0x20, 0x76, 0x61, 0x6c  …  0x33, 0x20, 0x7c, 0x20, 0x20, 0x20, 0x33, 0x20, 0x7c, 0x0a])
```
I would have expected something copy-pastable - how can I obtain that? I'd prefer not to write raw bytes to disk.

**Comment by maxfreu** [comment]
Sorry - should have read the function documentation :see_no_evil:

**Comment by tpapp** [comment]
No worries. If you think I can improve the docs or the README, don't hesitate to let me know in an issue. I didn't generate docs since it is a single function.
